version: "3.8"

services:
  webapp:
    image: robinirinformatica/webapp:latest
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://database:27017/mydatabase
    depends_on:
      - database

  database:
    image: mongo:4.4.6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  tests:
    image: robinirinformatica/webapp:latest
    depends_on:
      - webapp
    build:
      context: .
    volumes:
      - .:/app
    command: ["yarn", "test-api"]
    environment:
      - API_URL=http://webapp:3000

volumes:
  mongodb_data:
