version: "3.8"

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://database:27017/mydatabase
    depends_on:
      - database

  database:
    image: mongo:4.4.6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  tests:
    image: webapp
    depends_on:
      - webapp
    command: ["yarn", "test", "test.spec.js"]
    environment:
      - API_URL=http://webapp:3000

volumes:
  mongodb_data:
