---
name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install Node.js and project dependencies
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Navigate to the project directory
        run: cd ${{ github.workspace }}
        working-directory: ${{ github.workspace }}

      - name: Install project dependencies
        run: yarn install

      - name: Lint the project
        run: yarn lint
